### PR TITLE
Fix issue #128 - Refactor About Page

### PR DESCRIPTION
**Pull request by ZJaf**
- Added pictures to the Public/img
- Updated CSS and Sass files
- Created About.js component
- Added Hero picture to the asset folder

### CODE REVIEW

**Comment by RichardLitt** [comment]
Looks good to me! @VernL sorry for sniping you - let me know if you got thoughts!

**Comment by Jojokats** [comment]
I just ran npm run watch-css in my files.
and there's an error in the About.scss, the variable $background-dkGrey was not updated. but will fix this.

**Comment by RichardLitt** [comment]
@Jojokats Great. open a separate issue so this isn't logged in a closed PR!

**Comment by RichardLitt** [comment]
@Jojokats Great. open a separate issue so this isn't logged in a closed PR!

**Comment by Jojokats** [comment]
ok

**Pull request merged**
