### PR TITLE
Build(index.js): Saying "hello" with express routing

### PR DESCRIPTION
**Pull request by ZJaf**
This is a basic index.js file require express and printing "hello world"

### CODE REVIEW

**Comment by RichardLitt** [comment]
Cool. Which issue is this helping to close? Why did you make this PR? 

(Non-rhetorical, simple questions I know the answer to, but want you to answer).

**Comment by ZJaf** [comment]
YES! You are right! 
This PR is addressing the issue

**Comment by RichardLitt** [comment]
Cool. Let's work on the wording a bit more - the most important part of computer science is phrasing. 

Close. Take a look at [this article](https://github.com/erlang/otp/wiki/Writing-good-commit-messages). 

Then look at some PRs for popular projects:
- https://github.com/reactjs/redux/pulls
- https://github.com/angular/angular/pulls
- https://github.com/atom/atom/pulls

Can you change the title to something better?

**Comment by RichardLitt** [comment]
This is a much better name for this PR! Well done. 

However, this PR also adds index files, and it doesn't need to. Can you figure out how to only PR the express file, and remove the other files and their commits? :) This might be tricky!

**Comment by ZJaf** [comment]
@RichardLitt sorry for the src folder! I just fixed it back. The src is an old change that I don't know why happened to be updated today.

**Comment by RichardLitt** [comment]
Cool. @ZJaf I'm a bit confused - what is in this PR now? There's only whitespace changes, which aren't necessary for us. Should we close this, you think?

**Comment by ZJaf** [comment]
This is what I got from rebase! I removed my changes. But there is the gitignore change which is addressing issue #46. I would merge it.

**Comment by RichardLitt** [comment]
Skim or read [this article on keeping a clean git history](http://mat-mcloughlin.net/2015/06/27/keeping-a-clean-git-history/). There are others you can find, if you google those terms (clean, history, git). 

Then: Do you still think we should merge this? Or is there a better option?

**Comment by ZJaf** [comment]
Thanks for the article! I wish sometimes I could delete my fork and made a new one. Do everything clean! coz I tried different things and now all my branches are suffering. Would it be possible to close this PR, I clean up my branches and get back to you with a new PR with only gitignore issue?

**Comment by RichardLitt** [comment]
> Would it be possible to close this PR, I clean up my branches and get back to you with a new PR with only gitignore issue?

Yep!

**Pull request closed without merging**
