### PR TITLE
update: Add .css to gitignore and remove gulpfile

### PR DESCRIPTION
**Pull request by VernL**
- CSS files are build products
- SASS files are compiled by webpack

### CODE REVIEW

**Comment by RichardLitt** [comment]
@Jojokats This look OK to you?

**Comment by Jojokats** [comment]
> @Jojokats This look OK to you?

Not sure why we are adding css files to gitignore. 
Removing gulpfile  is fine since I had stopped using it.

**Comment by RichardLitt** [comment]
.css isn't the same as css/. These are just build products that shouldn't be checked in.

**Comment by Jojokats** [comment]
ok, thanks

**Pull request merged**
