### PR TITLE
Create index.html with blue bg and index.js

### PR DESCRIPTION
**Pull request by hammerhead79**
Add index.html, blue bg and index.js

### CODE REVIEW

**Comment by RichardLitt** [comment]
Hey, thanks!

Let's work a bit more at this PR. What does `Bookshelf` mean? And what does `Test` mean? 

Recommended reading: [Writing good commit messages](https://github.com/erlang/otp/wiki/Writing-good-commit-messages), [writing good PRs](https://github.com/blog/1943-how-to-write-the-perfect-pull-request). 

Try editing the content above after reading these.

**Comment by RichardLitt** [comment]
You should also be able to add a note here that will close the relevant issue. [Check this out](https://github.com/blog/1506-closing-issues-via-pull-requests).

**Comment by RichardLitt** [comment]
How's it going @hammerhead79? Any questions?

**Comment by hammerhead79** [comment]
I'm learning react. 
what's next?

**Comment by RichardLitt** [comment]
Let's close this PR. :) 

See the comment above.

**Comment by hammerhead79** [comment]
Index blue bg closed.

**Comment by RichardLitt** [comment]
Whoa! No, let's not close it like that! Let's figure out how to make the PR good enough to be merged. :)

**Comment by RichardLitt** [comment]
Let's work a bit more at this PR. What does `Bookshelf` mean? And what does `Test` mean? 

Recommended reading: [Writing good commit messages](https://github.com/erlang/otp/wiki/Writing-good-commit-messages), [writing good PRs](https://github.com/blog/1943-how-to-write-the-perfect-pull-request). 

Try editing the content above after reading these.

**Comment by hammerhead79** [comment]
Sorry, Bro!

I came up with a name Bookshelf because I first thought that I was creating a local copy of a travel shelf but then I realized it's a git branch and renamed bookshelf to index.

Test means I was just testing it out if it worked. I should've written "added blue background"

Sorry, I'm not good at expressing myself and writing and I needed to work on my communication.

Thank you! for taking your time for guiding and helping us.

**Comment by RichardLitt** [comment]
> Sorry, I'm not good at expressing myself and writing and I needed to work on my communication.

No need to apologize! We're here to get better at this, right? 

What do you think a better title would be than 'Index'? If you can't think of something, take a look at some more popular projects on GitHub and look at some PRs for them.

**Comment by hammerhead79** [comment]
Do you mean a title for our project? or for the blue background?
I thought you are just testing us if we know git

Title: Columbus, Voyages, New World, Nomads BookCase/Shelving...

Can you give me an example? What do you suggest?

**Comment by RichardLitt** [comment]
Sorry, I've not been very clear (all the time). 

`Index` is not a good name for a pull request. It doesn't tell me anything. What does this PR do? Rename it.

**Comment by RichardLitt** [comment]
Thanks! This satisfies #30.

**Pull request merged**
