### PR TITLE
Build React structure for home page - Fix issue #51

### PR DESCRIPTION
**Pull request by ZJaf**
I am not sure if the section which holds the picture of bookstores should be called portfolio or not. the rest of the components are almost presenting main containers in each section of the site.

### CODE REVIEW

**Comment by Jojokats** [comment]
Not sure, but I think it can be like an index of features book stores.

**Comment by RichardLitt** [comment]
Let's put some content in the files, first. Otherwise, what we have is empty files in `master`, which doesn't necessarily help anyone.

**Comment by RichardLitt** [comment]
Hey @ZJaf! This hasn't been changed, and isn't useful at the moment (it's not a significant code change). Closing this, but feel free to open a new one with more substantial changes. :)

**Comment by ZJaf** [comment]
I would have merged it! and it would make the life of me and Jonna easier today! to have same structure to build upon. 
No worries. 
We did it by looking over the shoulder of each other.

**Pull request closed without merging**
