### PR TITLE
Upload images and update index.html, styles.scss

### PR DESCRIPTION
**Pull request by Jojokats**
Hi @RichardLitt, I've updated the index.html and added images. What do you think, any changes you want me to do? :)

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks @Jojokats!

A small note; for many of your PRs, you have said something like "Could you please merge it into master?" or "this PR is now ready to merge." It's great that you're so keen to be in the repo - but this kind of comment isn't helpful, because it puts pressure on the reviewer to merge your contributions. Your contributions should stand on their own merit. By asking them to be merged, you're saying "I think this is good enough." But you already say that by opening the PR in the first place. It's the decision of the reviewer as to whether or not code should be merged, and it seems a bit audacious to tell the reviewer that they don't need to do their job. Again, I know you're coming from the right place, but the wording isn't perceived well by me, at least.

**Comment by RichardLitt** [comment]
I love this PR!

Where did you get the images from? Are they licensed appropriately?

**Comment by Jojokats** [comment]
You’re right Richard! Sorry about that.

I am more than happy to reword it, not sure what to say.
- Here is my PR?

Can you please advise,
Thanks!

Joanna

**Comment by RichardLitt** [comment]
yeah! Something like "I did this! What do you think?" works. :)

**Comment by Jojokats** [comment]
Thanks @Richard. 
I got them all at pixels or unsplash so they are free to use!!!

What do you think we should do about the fonts?

- J

**Comment by RichardLitt** [comment]
Great. Do we need to credit them somewhere? 

I like the fonts in this PR. Do you wan to open an issue with the email you sent me about fonts, so the others can weigh in, and so that all decisions are tracked in this repo? Also - the PDF you sent doesn't seem like it was rendered correctly.

**Comment by Jojokats** [comment]
Hey Richard
I updated the comment, :)

I’m glad you like the index.html.

**Comment by RichardLitt** [comment]
@Jojokats make sure we don't need to reference that we got the images somewhere!

**Comment by Jojokats** [comment]
Hey @RichardLitt , 
I did a git merge origin/master but not sure it's showing up. I modified the index.html & replaced the image. Can you please advise?
Thanks!

**Comment by RichardLitt** [comment]
I already merged it. Please open a new PR!

**Comment by Jojokats** [comment]
> I already merged it. Please open a new PR!

I tried but my homebranch is not showing up.

**Comment by RichardLitt** [comment]
Can you show me a git graph output? 

Make a new branch with your local commits.

**Comment by Jojokats** [comment]
> Can you show me a git graph output?

Don't know how to do this...

**Comment by RichardLitt** [comment]
Google "git graphs". I got this result: https://stackoverflow.com/questions/1057564/pretty-git-branch-graphs

**Comment by Jojokats** [comment]
> Can you show me a git graph output?

Article looks confusing, can I just run this to give you a git graph?
`git log --all --decorate --oneline --graph`

**Comment by RichardLitt** [comment]
> Article looks confusing, can I just run this to give you a git graph?

What's confusing about it? 

That looks right, sure. Just take a screenshot or copy the text here.

**Comment by Jojokats** [comment]
> That looks right, sure. Just take a screenshot or copy the text here.

```
git log --all --decorate --oneline --graph
* 0c8dbef (HEAD -> homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
:...skipping...
* 0c8dbef (HEAD -> homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
| *   7c61232 Merge pull request #50 from ZJaf/gitignore
:...skipping...
* 0c8dbef (HEAD -> homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
| *   7c61232 Merge pull request #50 from ZJaf/gitignore
| |\  
:...skipping...
* 0c8dbef (HEAD -> homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
| *   7c61232 Merge pull request #50 from ZJaf/gitignore
| |\  
| | * 41d4214 Fixed issue #46: added Ds_store
:...skipping...
* 0c8dbef (HEAD -> homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
| *   7c61232 Merge pull request #50 from ZJaf/gitignore
| |\  
| | * 41d4214 Fixed issue #46: added Ds_store
| * | 2871433 (origin/docs/2017-10-17) Add maps.html #43
:...skipping...
* 0c8dbef (HEAD -> homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
| *   7c61232 Merge pull request #50 from ZJaf/gitignore
| |\  
| | * 41d4214 Fixed issue #46: added Ds_store
| * | 2871433 (origin/docs/2017-10-17) Add maps.html #43
| |/  
:...skipping...
* 0c8dbef (HEAD -> homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
| *   7c61232 Merge pull request #50 from ZJaf/gitignore
| |\  
| | * 41d4214 Fixed issue #46: added Ds_store
| * | 2871433 (origin/docs/2017-10-17) Add maps.html #43
| |/  
| | *   66f23e5 (refs/stash) WIP on homepage: dd0d2d6 Merge from masterMerged fr:...skipping...
* 0c8dbef (HEAD -> homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
| *   7c61232 Merge pull request #50 from ZJaf/gitignore
| |\  
| | * 41d4214 Fixed issue #46: added Ds_store
| * | 2871433 (origin/docs/2017-10-17) Add maps.html #43
| |/  
| | *   66f23e5 (refs/stash) WIP on homepage: dd0d2d6 Merge from masterMerged from Master branch, resolved conflicts.
:...skipping...
* 0c8dbef (HEAD -> homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
| *   7c61232 Merge pull request #50 from ZJaf/gitignore
| |\  
| | * 41d4214 Fixed issue #46: added Ds_store
| * | 2871433 (origin/docs/2017-10-17) Add maps.html #43
| |/  
| | *   66f23e5 (refs/stash) WIP on homepage: dd0d2d6 Merge from masterMerged from Master branch, resolved conflicts.
| | |\  
:...skipping...
* 0c8dbef (HEAD -> homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
| *   7c61232 Merge pull request #50 from ZJaf/gitignore
| |\  
| | * 41d4214 Fixed issue #46: added Ds_store
| * | 2871433 (origin/docs/2017-10-17) Add maps.html #43
| |/  
| | *   66f23e5 (refs/stash) WIP on homepage: dd0d2d6 Merge from masterMerged from Master branch, resolved conflicts.
| | |\  
| |/ /  
:...skipping...
* 0c8dbef (HEAD -> homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
| *   7c61232 Merge pull request #50 from ZJaf/gitignore
| |\  
| | * 41d4214 Fixed issue #46: added Ds_store
| * | 2871433 (origin/docs/2017-10-17) Add maps.html #43
| |/  
| | *   66f23e5 (refs/stash) WIP on homepage: dd0d2d6 Merge from masterMerged from Master branch, resolved conflicts.
| | |\  
| |/ /  
|/| |   
:

```

**Comment by RichardLitt** [comment]
Looks like you have a good commit. Create a new branch and push it to your remote, with the commit 0c8dbef on it. Then open a PR from there.

**Comment by Jojokats** [comment]
> Looks like you have a good commit. Create a new branch and push it to your remote, with the commit 0c8dbef on it. Then open a PR from there.

Will try... but not sure about  **"commit 0c8dbef"**

**Comment by RichardLitt** [comment]
What are you not sure about?

**Comment by Jojokats** [comment]
> What are you not sure about?

Not sure how to do this.

**Comment by RichardLitt** [comment]
- Create a new branch
- push it to your remote
- Ensure that commit 0c8dbef is on it.

Which step is confusing? What step have you not been able to figure out by Googling?

**Comment by Jojokats** [comment]
Will look into it. Thanks!

**Pull request merged**
