### PR TITLE
Feat: replace D3 map with leaflet and add bookstores

### PR DESCRIPTION
**Pull request by VernL**
- Leaflet map is better suited for our application.
- Removed D3 packages and added leaflet packages.
- Added basic leaflet map.
- Added several bookstores for testing purposes.

### CODE REVIEW

**Comment by VernL** [comment]
View in action @ https://secret-eyrie-53788.herokuapp.com/map

**Comment by VernL** [comment]
Images are currently broken in master, a live version is available [here](https://secret-eyrie-53788.herokuapp.com/map)

**Comment by RichardLitt** [comment]
So... is this ready to go, or not?

**Comment by VernL** [comment]
Yes, ready to go

**Comment by VernL** [comment]
The images are broken due to an issue that is outside the scope of this PR. The fix will be PR'ed after this one is dealt with.

**Comment by RichardLitt** [comment]
Use this for the Word: http://wordbookstore.ca/wp-content/uploads/2015/08/The-Word-08.jpg

**Comment by RichardLitt** [comment]
Otherwise looks fine to me.

**Pull request merged**
