### PR TITLE
Modified padding to center navbar 

### PR DESCRIPTION
**Pull request by Jojokats**
Adjusted padding-top of the navbar to center it.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Hey @Jojokats, thanks for opening this PR. Unfortunately, you have included many commits in this PR which are not related to the work you're hoping to merge, in commit ddd8dca. Please only include commits you need to in PRs. 

To fix this, put ddd8dca on it's own branch off of master.

**Comment by Jojokats** [comment]
I only did one commit in this branch:
```
commit ddd8dcaf7c393063ecb848b9707737d7caf50702 (origin/feat/navbar-padding, feat/navbar-padding)
Author: Joanna <morningstarjk@hotmail.com>
Date:   Tue Oct 31 21:44:58 2017 -0400

    Modified navbar padding
```

**Comment by RichardLitt** [comment]
Please read up on branches. I do not have the energy to help you here. When you've learned how this works, you will be able to understand my comment and change this pull request accordingly.

**Comment by Jojokats** [comment]
Hey @RichardLitt,  no worries, I will clean this up.

**Pull request closed without merging**
