### PR TITLE
issue43 added a new file maps.html

### PR DESCRIPTION
**Pull request by hammerhead79**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Cool. Note: You can use `#43` instead of `issue43` on GitHub to make it refer. However, in vim, never start a line with a `#`, as it will be commented out. Maybe reorder the name of this PR? `Add maps.html #43`? 

Learn how to use `git commit --amend` and `git push --force hammerhead79 issue43` to change the commit name, too.

**Comment by RichardLitt** [comment]
@hammerhead79 I would have waited a bit to merge this. Can you add a route so that I can go to `localhost:4000/maps` and see this file?

**Comment by hammerhead79** [comment]
Sorry! bro, I thought I was doing it on my own Fork. I will see if I can undo it. 
I also need to learn how to route pages.

**Comment by RichardLitt** [comment]
Don't spend too much time on undoing it - hard to do with a merge. Maybe just open a new PR?

**Pull request merged**
