### PR TITLE
Homepage react-Navigation Bar without search input

### PR DESCRIPTION
**Pull request by ZJaf**
I needed to bring img and css folder inside src so that react components can see them.

I decided to only have the navbar and deleted the menu component. We can decide to have Menu as a separated component later. 

I also added router on top of the nav_bar component.

### CODE REVIEW

**Comment by RichardLitt** [comment]
> I needed to bring img and css folder inside src so that react components can see them.

Why can't you have a relative path with `../../img/...`? The two dots will go up a folder. You shouldn't need to move them.

**Comment by ZJaf** [comment]
I initially started with that, but it was bugging that it needs to be inside src folder. I guess the reason is importing the files in React and it needs to be in the scope. 

I suggest we delete the index and all the mockup related files when we reactify the whole website.

**Comment by RichardLitt** [comment]
Is there any way to do it piecemeal, besides moving everything in?

**Comment by ZJaf** [comment]
I had the same intention, to make only small changes (just the menu in the react). Unfortunately, all the code is necessary for that small change.  kinda like an infrastructure for the building.

**Comment by RichardLitt** [comment]
@ZJaf Works for me. Can you do it in a branch? If not, just go for it - make sure that you and @Jojokats work together. 

Unfortunately I merged @VernL's code before taking into account that yours was earlier. Can you rebase? Sorry about this!

**Comment by RichardLitt** [comment]
@VernL Can you test the routing for this?

**Comment by RichardLitt** [comment]
@VernL Any word on this?

**Comment by ZJaf** [comment]
As we continued with the files that Vernon designed, I guess there is no point continuing with my files. It is pretty the same. @RichardLitt  If you are OK, I close this PR

**Comment by RichardLitt** [comment]
:) Thanks @ZJaf!

**Pull request closed without merging**
