### PR TITLE
Add not found page

### PR DESCRIPTION
**Pull request by WellingGuzman**
I don't know if using switch is the best option (_or the only option_) but I had to implement the not found page using switch.

Ref: #230 This PR is independent from #231

### CODE REVIEW

**Comment by RichardLitt** [comment]
Can you find a reason why switch would not be OK? :)

**Comment by WellingGuzman** [comment]
I do find a reason why it's OK, their docs: https://reacttraining.com/react-router/web/example/no-match

I pointed that out, as I've never used the library before and it probably be other way around that could be better, just making a point, if someone knew another one. Newbie opinion to save myself.

**Comment by WellingGuzman** [comment]
From docs:

> A \<Switch\> renders the first child <Route> that matches. A <Route> with no path always matches.

**Comment by VernL** [comment]
This looks like a good use of a Switch to me. Could you please git rebase to resolve the merge conflict and update the PR?

**Comment by WellingGuzman** [comment]
I resolved the conflict.

**Comment by VernL** [comment]
Awesome. In an effort to keep our commit history clean, we've avoided adding redundant Merge commit's to our codebase. Instead of merging, we've favored rebasing. It's good practice and helps keep the logs clean! From the current state of your branch, I believe you could reset your branch to your previous commit than run `git rebase master` (first making sure master is up to date). Hit me up on slack if this is unclear!

**Comment by VernL** [comment]
Looks good, thanks!

**Pull request merged**
