### PR TITLE
Add CoC, Contributing, License, edited README

### PR DESCRIPTION
**Pull request by RichardLitt**
Hey all. I added you here as reviewers. 

I'd like you to look at the Files changed, and give me a sign off on how they look, or to raise any issues by commenting here. GitHub has a guide on how to sign off on a code review, [here](https://help.github.com/articles/about-pull-request-reviews/). Normally, we won't need everyone to sign off on something - but as this is a PR that has to deal with community stuff (licensing, code of conduct), I want to make sure you all read it and understand what is going on. 

Here we go!

### CODE REVIEW

**Comment by RichardLitt** [comment]
Alternatively, for now, you can simply say this: "LGTM". It means "Looks good to me."

Take a look at the "Files changed" tab above first, though.

**Comment by Jojokats** [comment]
Hey all, read it and LGTM!
Cheers!

**Comment by hammerhead79** [comment]
LGTM

**Comment by HanieJ** [comment]
LGTM ! what are pinks lines?!

**Comment by RichardLitt** [comment]
Pink lines have been deleted, green have been added. Note: a line is marked as deleted if it is moved to a different file (as has happened here).

**Pull request merged**
