### PR TITLE
Added about.html and the images

### PR DESCRIPTION
**Pull request by Jojokats**
Added the about.html and the images.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Rebase?

**Comment by Jojokats** [comment]
oh no!!

**Comment by Jojokats** [comment]
You were supposed to merge About.html first!

**Comment by RichardLitt** [comment]
That one hasn't been merged yet.

**Comment by Jojokats** [comment]
It's different. I added the paragraph you wrote today and added the slogans for each one of us and made tweaks

**Comment by Jojokats** [comment]
This one is the good one, the updated one

**Comment by RichardLitt** [comment]
Great. Which one should be merged? Right now, they both need to be rebased.

**Comment by Jojokats** [comment]
You can delete 
>Added about.html #109

I made changes and the good one is #121

**Comment by Jojokats** [comment]
I don't know how to rebase, sorry!

**Comment by Jojokats** [comment]
I don't understand why it has conflicts only in the
`design/css/style.css`

**Comment by RichardLitt** [comment]
Cool. Two good practices: 1) Close your PRs that aren't relevant anymore. 2) Fix any conflicts yourself. It shouldn't be up to the reviewer to see why there is a conflict. Try rebasing off of master, and manually seeing why there was a conflict. :)

**Pull request closed without merging**
