### PR TITLE
feat: create map page and add basic d3 map of Montreal 

### PR DESCRIPTION
**Pull request by VernL**
- create map component with basic styles
- add d3 package and integrate with react 
- add basic map of montreal using Montreal's open data

referenced to issue #180

### CODE REVIEW

**Comment by RichardLitt** [comment]
Uh. Ok, so, why can't I run this? 

```
15:25 ~/src/the-travel-shelf (feat/map) * 🐕  npm run dev

> the-travel-shelf@1.0.0 dev /Users/richard/src/the-travel-shelf
> concurrently "npm run backend" "react-scripts start"

[0]
[0] > the-travel-shelf@1.0.0 backend /Users/richard/src/the-travel-shelf
[0] > node ./backend/bin/www
[0]
[0] /Users/richard/src/the-travel-shelf/backend/routes/bookstores.js:12
[0]   let newStore = new db.Bookstore({...req.body})
[0]                                    ^^^
[0]
[0] SyntaxError: Unexpected token ...
```

**Comment by VernL** [comment]
Are you using node": "8.9.1?

**Comment by RichardLitt** [comment]
ok, next issue:

```
Failed to compile
./src/scenes/Map/Map.js
Module not found: Can't resolve './Map.css' in '/Users/richard/src/the-travel-shelf/src/scenes/Map'
```

**Comment by VernL** [comment]
npm run watch-css is not automatically run with npm run dev. I'll open an issue and have a look.

**Comment by RichardLitt** [comment]
Got it. Good start. 

Things to do: 
- [ ] Add a heading saying 'Montreal'. 
- [ ] Remove blue shading for unnecessary townships
- [ ] Add some dummy data if you don't have bookstores yet
- [ ] Add a tooltip or popup with the name of the bookstore and a link to the store index page

And then I think we can merge. I think these are trivial.

**Comment by RichardLitt** [comment]
Having an issue with this. Errors:


Navigated to http://localhost:3000/Map
react-dom.development.js:15374 Download the React DevTools for a better development experience: https://fb.me/react-devtools
bookstores.js:19 GET http://localhost:3000/api/bookstores 500 (Internal Server Error)
(anonymous) @ bookstores.js:19
(anonymous) @ index.js:11
fetchStores @ App.js:44
componentDidMount @ App.js:22
commitLifeCycles @ react-dom.development.js:8770
commitAllLifeCycles @ react-dom.development.js:9946
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
commitRoot @ react-dom.development.js:10050
performWorkOnRoot @ react-dom.development.js:11017
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
scheduleTopLevelUpdate @ react-dom.development.js:11193
updateContainer @ react-dom.development.js:11231
(anonymous) @ react-dom.development.js:15226
unbatchedUpdates @ react-dom.development.js:11102
renderSubtreeIntoContainer @ react-dom.development.js:15225
render @ react-dom.development.js:15290
./src/index.js @ index.js:15
__webpack_require__ @ bootstrap fde3b2b5c39e25800fb1:669
fn @ bootstrap fde3b2b5c39e25800fb1:87
0 @ bookstores.js:28
__webpack_require__ @ bootstrap fde3b2b5c39e25800fb1:669
(anonymous) @ bootstrap fde3b2b5c39e25800fb1:715
(anonymous) @ bundle.js:719
bookstores.js:28 Error Fetching Stores Error: 500
    at bookstores.js:22
    at <anonymous>
bookstores.js:19 Fetch failed loading: GET "http://localhost:3000/api/bookstores".
(anonymous) @ bookstores.js:19
(anonymous) @ index.js:11
fetchStores @ App.js:44
componentDidMount @ App.js:22
commitLifeCycles @ react-dom.development.js:8770
commitAllLifeCycles @ react-dom.development.js:9946
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
commitRoot @ react-dom.development.js:10050
performWorkOnRoot @ react-dom.development.js:11017
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
scheduleTopLevelUpdate @ react-dom.development.js:11193
updateContainer @ react-dom.development.js:11231
(anonymous) @ react-dom.development.js:15226
unbatchedUpdates @ react-dom.development.js:11102
renderSubtreeIntoContainer @ react-dom.development.js:15225
render @ react-dom.development.js:15290
./src/index.js @ index.js:15
__webpack_require__ @ bootstrap fde3b2b5c39e25800fb1:669
fn @ bootstrap fde3b2b5c39e25800fb1:87
0 @ bookstores.js:28
__webpack_require__ @ bootstrap fde3b2b5c39e25800fb1:669
(anonymous) @ bootstrap fde3b2b5c39e25800fb1:715
(anonymous) @ bundle.js:719
abstract-xhr.js:132 XHR finished loading: GET "http://localhost:3000/sockjs-node/info?t=1515800029268".
./node_modules/sockjs-client/lib/transport/browser/abstract-xhr.js.AbstractXHRObject._start @ abstract-xhr.js:132
(anonymous) @ abstract-xhr.js:21
setTimeout (async)
AbstractXHRObject @ abstract-xhr.js:20
XHRLocalObject @ xhr-local.js:8
InfoAjax @ info-ajax.js:19
./node_modules/sockjs-client/lib/info-receiver.js.InfoReceiver._getReceiver @ info-receiver.js:36
./node_modules/sockjs-client/lib/info-receiver.js.InfoReceiver.doXhr @ info-receiver.js:56
(anonymous) @ info-receiver.js:25
setTimeout (async)
InfoReceiver @ info-receiver.js:24
SockJS @ main.js:121
./node_modules/react-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:49
__webpack_require__ @ bootstrap fde3b2b5c39e25800fb1:669
fn @ bootstrap fde3b2b5c39e25800fb1:87
0 @ bookstores.js:28
__webpack_require__ @ bootstrap fde3b2b5c39e25800fb1:669
(anonymous) @ bootstrap fde3b2b5c39e25800fb1:715
(anonymous) @ bundle.js:719
favicon.ico:1 GET http://localhost:3000/favicon.ico 500 (Internal Server Error)
webpackHotDevClient.js:126 ./src/components/StoreCard/StoreCard.js
  Line 10:  Redundant alt attribute. Screen-readers already announce `img` tags as an image. You don't need to use the words `image`, `photo,` or `picture` (or any specified custom words) in the alt prop  jsx-a11y/img-redundant-alt
printWarnings @ webpackHotDevClient.js:126
handleWarnings @ webpackHotDevClient.js:143
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:196
./node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
./node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
webpackHotDevClient.js:126 ./src/components/StoreArticle/StoreArticle.js
  Line 45:  Anchors must have content and the content must be accessible by a screen reader  jsx-a11y/anchor-has-content
  Line 46:  Anchors must have content and the content must be accessible by a screen reader  jsx-a11y/anchor-has-content
  Line 47:  Anchors must have content and the content must be accessible by a screen reader  jsx-a11y/anchor-has-content
  Line 54:  Anchors must have content and the content must be accessible by a screen reader  jsx-a11y/anchor-has-content
  Line 55:  Anchors must have content and the content must be accessible by a screen reader  jsx-a11y/anchor-has-content
  Line 56:  Anchors must have content and the content must be accessible by a screen reader  jsx-a11y/anchor-has-content
  Line 57:  Anchors must have content and the content must be accessible by a screen reader  jsx-a11y/anchor-has-content
printWarnings @ webpackHotDevClient.js:126
handleWarnings @ webpackHotDevClient.js:143
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:196
./node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
./node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35

**Comment by RichardLitt** [comment]
Do I need to update my db?

**Comment by VernL** [comment]
The contents of the database has changed, however unless you are running locally you should have the latest.

I did rebase as backend/models/bookstore.js was not up to date.

**Comment by VernL** [comment]
How can we trouble shoot this?

**Comment by VernL** [comment]
Is it possible that the .env file with db credentials is missing?

**Comment by RichardLitt** [comment]
I am running it locally. How else am I supposed to test this branch?

**Comment by RichardLitt** [comment]
Still failing to get get api/bookstores. Any ideas there?

**Pull request merged**
