### PR TITLE
Newhomepage

### PR DESCRIPTION
**Pull request by Jojokats**
I modified the index.html and replaced the map image. Let me know if there are other changes. Thanks!

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks @Jojokats. 

Please rebase this off of `master`. There should not be a merge commit in the history, either.

**Comment by Jojokats** [comment]
> Please rebase this off of master. There should not be a merge commit in the history, either.

Not sure how to do this. I only know basic git commands.

**Comment by RichardLitt** [comment]
@Jojokats I know you do not know how to do this. I expect you to _learn_ how to do it. If you're unsure, please google it, and only if you can't find something to guide you after 15 minutes, then let me know. 

For instance, google: "How to rebase".

**Comment by Jojokats** [comment]
>For instance, google: "How to rebase".

OK, but first I need to make a really strong espresso !

**Comment by RichardLitt** [comment]
> OK, but first I need to make a really strong espresso !

I just had my fourth coffee of the day. Welcome to coding. 💃

**Comment by Jojokats** [comment]
@RichardLitt can you please confirm if the following is correct:

>Please rebase this off of master

 1- fetch the new master from the upstream repository, then rebase your work branch on that:

`git fetch origin`            # Updates origin/master
`git rebase origin/master`    # Rebases current branch onto origin/master

**Comment by RichardLitt** [comment]
Either looks right to me. Google a tutorial to explain how to do it a bit cleaner - those commands are missing some information (what branch will you be on when you run `git rebase`, for instance)

**Comment by Jojokats** [comment]
>(what branch will you be on when you run git rebase, for instance)

I'm on the newhomepage branch I just created.

They mention:
> First fetch the new master from the upstream repository, then rebase your work branch on that:

but what is upstream repository. Guess I should ask Google...

**Comment by RichardLitt** [comment]
> Guess I should ask Google...

yes.

**Comment by Jojokats** [comment]
> but what is upstream repository. Guess I should ask Google...

`‘origin/master’ is the “upstream” of ‘master’.`

When I do a git status, I get:
`On branch newhomepage`
`Your branch is up-to-date with 'origin/newhomepage'. `

So can I now just run:

`git fetch origin # Updates origin/master`
`git rebase origin/master # Rebases current branch onto origin/master`

**Comment by RichardLitt** [comment]
Yes, try that. 

It would be great if you could test it without asking me if that's what you should do. The cycle time between response and action is costly - it's much better if you try it yourself, and see if it works. If it doesn't, try something else.

**Comment by Jojokats** [comment]
> It would be great if you could test it without asking me if that's what you should do. The cycle time between response and action is costly - it's much better if you try it yourself, and see if it works. If it doesn't, try something else.

I did not want to run something in the terminal, that I shouldn't since I'm embarking on new grounds and prefer to ask prior to breaking something.

**Comment by Jojokats** [comment]
I'm having an issue:
```git fetch origin 
JoannaKats:the-travel-shelf joannakatsifaraki$ git rebase origin/master
Cannot rebase: You have unstaged changes.
Please commit or stash them.
JoannaKats:the-travel-shelf joannakatsifaraki$ git status
On branch newhomepage
Your branch is up-to-date with 'origin/newhomepage'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    img/world.png

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.DS_Store
	img/.DS_Store
	src/.DS_Store

no changes added to commit (use "git add" and/or "git commit -a")
```
I already did a commit for the index.html & worldmap
 ```git add index.html
JoannaKats:the-travel-shelf joannakatsifaraki$ git add img/worldmap2.jpg
JoannaKats:the-travel-shelf joannakatsifaraki$ git status
On branch homepage
```

I also did a commit :
`git commit -m "Modified index.html and replaced world image"`

so now I don't know how to proceed.

**Comment by RichardLitt** [comment]
> Cannot rebase: You have unstaged changes.

This means you have some local files which have changed. It tells you which ones. There should be no changes - commit or stash the changes, then try again. 

You also need to add `.DS_Store` to your global .gitignore.

**Comment by Jojokats** [comment]
> You also need to add .DS_Store to your global .gitignore.
 I added it and made a commit.

Now, I don't understand how to proceed. 
> commit or stash the changes, then try again.

I made the commit, but don't understand ***stash***, then try what again?

**Comment by Jojokats** [comment]
So maybe it will be easier to continue tomorrow at the meeting.

**Comment by RichardLitt** [comment]
@Jojokats, I think the issue is with your process, not with the instructions. Put it another way: _What do you do when you don't know what to do next?_

Let's look at this:
> You also need to add .DS_Store to your global .gitignore.

Which you say you don't understand. Telling me you don't understand helps in that you can ask me, but I do not have limitless resources. So, you need to find another way to learn how to find the answer.

What do you think you could google to find the answer from "you also need to add .DS_Store to your global .gitignore."?

**Comment by Jojokats** [comment]
I already added the .Ds_Store to .gitignore

**Comment by Jojokats** [comment]
At this point, I think the best thing I can do is to take a comprehensive course on git to clarify a lot of issues, which I will do starting today.

**Comment by RichardLitt** [comment]
I don't think you have. They wouldn't come up as "Untracked files" if you had. 

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.DS_Store
	img/.DS_Store
	src/.DS_Store
```

**Comment by Jojokats** [comment]
I only added .DS_Store, not the rest of them

**Comment by RichardLitt** [comment]
Do you know what a global .gitignore file is?

**Comment by Jojokats** [comment]
I guess not really!

**Comment by Jojokats** [comment]
So, I think at this point, I'm not advancing as I would like, so I'm planning on focusing on a git course to better understand how all this works.

**Comment by RichardLitt** [comment]
> So, I think at this point, I'm not advancing as I would like, so I'm planning on focusing on a git course to better understand how all this works.

I don't think this is the right approach. I think you know how to use Git. What you don't know is how to find specific answers to your questions. 

For instance, if you don't know what a global .gitignore is, google it. This is your #1 best resource of all time. It will help you. Google "What is a global gitignore file" or something similar.

The same for learning how to rebase. If you don't know the answer, try finding a way to phrase it as a google question, and seeing if you can find it.

**Comment by Jojokats** [comment]
I though I did a `global .gitignore ` till you asked me if I knew what it was, then realised I did it wrong. Or else I would have googled it.

**Comment by RichardLitt** [comment]
Cool. Perhaps I should have been clearer when I said "You need to add .DS_Store to your global gitignore". You may not have realized I asked that because those files are part of why you were unable to rebase. 

But the same could be said for `stash`. Try and figure out what `stash` means. It's a git command.

**Comment by Jojokats** [comment]
> Try and figure out what stash means. It's a git command.

git stash temporarily shelves (or stashes) changes you've made to your working copy so you can work on something else, and then come back and re-apply them later on. Stashing is handy if you need to quickly switch context and work on something else, but you're mid-way through a code change and aren't quite ready to commit.

**Comment by RichardLitt** [comment]
Cool. I know what git stashing is - no need to post it here. Does stashing or committing the files seem more appropriate? Do you want the unstaged changes to be in the new branch, or do you not? Pick one or the other.

**Comment by Jojokats** [comment]
I just ran: git status 
```
git status
On branch newhomepage
Your branch is up-to-date with 'origin/newhomepage'.
nothing to commit, working tree clean
```

**Comment by RichardLitt** [comment]
Sweet. Looks like you can keep rebasing. Try `git rebase`. It will probably ask you to continue your old rebase.

**Comment by Jojokats** [comment]
> Try git rebase. It will probably ask you to continue your old rebase.
I did and got the following:

```git rebase
First, rewinding head to replay your work on top of it...
Fast-forwarded newhomepage to refs/remotes/origin/newhomepage.
JoannaKats:the-travel-shelf joannakatsifaraki$ git status
On branch newhomepage
Your branch is up-to-date with 'origin/newhomepage'.
nothing to commit, working tree clean
```

**Comment by RichardLitt** [comment]
Small note: You need to put a space between lines. So that this:

```
> Try git rebase. It will probably ask you to continue your old rebase.
I did and got the following:
```

becomes this:

```
> Try git rebase. It will probably ask you to continue your old rebase.

I did and got the following:
```

Otherwise, the markdown doesn't work right.

**Comment by RichardLitt** [comment]
Awesome. Show me the graph again.

**Comment by Jojokats** [comment]
> Awesome. Show me the graph again.

```
 git log --all --decorate --oneline --graph
* 459165d (HEAD -> newhomepage, origin/newhomepage) Removed img/world.png
* fed224f Added .DS_Store to .gitignore file
* 0c8dbef (homepage) Modified index.html and replaced world image
*   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
|\  
* | 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
| *   ddd4fe9 (origin/master, origin/HEAD, master, issue-12345) Merge pull request #56 from RichardLitt/create-react-app
| |\  
| | * 0e155eb (origin/create-react-app) Add React and React-router
| |/  
| * 1f98dd2 Replace Leaflet with Google map with markers
| * dd7ee40 Added map.js #43
| *   14789f0 Merge pull request #36 from RichardLitt/homepage
| |\  
| | *   86e82e2 Merge branch 'master' into homepage
| | |\  
| |/ /  
|/| /   
| |/    
| *   7c61232 Merge pull request #50 from ZJaf/gitignore
| |\  
| | * 41d4214 Fixed issue #46: added Ds_store
| * | 2871433 (origin/docs/2017-10-17) Add maps.html #43
| |/  
| | *   66f23e5 (refs/stash) WIP on homepage: dd0d2d6 Merge from masterMerged from Master branch, resolved conflicts.
| | |\  
| |/ /  
:

```

**Comment by RichardLitt** [comment]
Cool. Now, you hvae a couple of extra commits in origin/newhomepage. You need to make sure that your origin/master matches the remote master. I'm not sure it does, looking at this. Can you make sure?

**Comment by Jojokats** [comment]
> You need to make sure that your origin/master matches the remote master. I'm not sure it does, 
looking at this. Can you make sure?

that means I have to checkout to master and do a git pull?

**Comment by RichardLitt** [comment]
Yep.

**Comment by Jojokats** [comment]
OK, so this is what I did:
```
git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

```
and switched to newhomepage:
```
git checkout newhomepage
Switched to branch 'newhomepage'
Your branch is up-to-date with 'origin/newhomepage'.
JoannaKats:the-travel-shelf joannakatsifaraki$ git status
On branch newhomepage
Your branch is up-to-date with 'origin/newhomepage'.
nothing to commit, working tree clean

```
so all is up to date.

**Comment by Jojokats** [comment]
It still says
> Conflicting files
index.html

**Comment by RichardLitt** [comment]
On branch newhomepage, try `git rebase master`? Then show me the graph again. We're trying to get rid of the merge commits in the history.

**Comment by RichardLitt** [comment]
What still says conflicting files? Are you editing index.html?

**Comment by Jojokats** [comment]
```git log --all --decorate --oneline --graph
* c5374a6 (origin/master, origin/HEAD, master) Added the .DS_Store files
| * 459165d (HEAD -> newhomepage, origin/newhomepage) Removed img/world.png
| * fed224f Added .DS_Store to .gitignore file
| * 0c8dbef (homepage) Modified index.html and replaced world image
| *   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
| |\  
| |/  
|/|   
| * 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
|/|   
* |   ddd4fe9 (issue-12345) Merge pull request #56 from RichardLitt/create-react-app
|\ \  
| * | 0e155eb (origin/create-react-app) Add React and React-router
|/ /  
* | 1f98dd2 Replace Leaflet with Google map with markers
* | dd7ee40 Added map.js #43
* |   14789f0 Merge pull request #36 from RichardLitt/homepage
|\ \  
| * \   86e82e2 Merge branch 'master' into homepage
| |\ \  
| |/ /  
|/| /   
| |/    
* |   7c61232 Merge pull request #50 from ZJaf/gitignore
|\ \  
| * | 41d4214 Fixed issue #46: added Ds_store
* | | 2871433 (origin/docs/2017-10-17) Add maps.html #43
:
```

**Comment by Jojokats** [comment]
> Are you editing index.html?

Yes, I had to write the new name of the image file in index.html

**Comment by Jojokats** [comment]
Forgot to do git rebase master

```
git rebase master
First, rewinding head to replay your work on top of it...
Applying: Upload images and update index.html, styles.scss
Applying: Modified index.html and replaced world image
Applying: Added .DS_Store to .gitignore file
Applying: Removed img/world.png
JoannaKats:the-travel-shelf joannakatsifaraki$ git log --all --decorate --oneline --graph
* 8307346 (HEAD -> newhomepage) Removed img/world.png
* fd95945 Added .DS_Store to .gitignore file
* d83a8a8 Modified index.html and replaced world image
* cc94849 Upload images and update index.html, styles.scss
* c5374a6 (origin/master, origin/HEAD, master) Added the .DS_Store files
| * 459165d (origin/newhomepage) Removed img/world.png
| * fed224f Added .DS_Store to .gitignore file
| * 0c8dbef (homepage) Modified index.html and replaced world image
| *   c799676 (origin/homepage) Merge remote-tracking branch 'origin/master' into homepage
| |\  
| |/  
|/|   
| * 7a3c392 Upload images and update index.html, styles.scss
| | * b010ced (origin/issue-59-fake-branch, issue-59-fake-branch) Fixes #59 fake issue
| |/  
|/|   
* |   ddd4fe9 (issue-12345) Merge pull request #56 from RichardLitt/create-react-app
|\ \  
| * | 0e155eb (origin/create-react-app) Add React and React-router
|/ /  
* | 1f98dd2 Replace Leaflet with Google map with markers
* | dd7ee40 Added map.js #43
* |   14789f0 Merge pull request #36 from RichardLitt/homepage
|\ \  
| * \   86e82e2 Merge branch 'master' into homepage
| |\ \  
| |/ /  
|/| /   
| |/    
:

```

**Comment by Jojokats** [comment]
Still says:
> Conflicting files
index.html

**Comment by RichardLitt** [comment]
`Git remote -vv`

**Comment by RichardLitt** [comment]
If there's a conflict, you need to commit the change, or stash it. If you edit a file, there will be a conflict. Try and figure out why - google `git conflict rebase why`. 

I'm out of time to help with this, today.

**Comment by Jojokats** [comment]
```
git remote -vv
origin	https://github.com/Jojokats/the-travel-shelf.git (fetch)
origin	https://github.com/Jojokats/the-travel-shelf.git (push)
upstream	https://github.com/RichardLitt/the-travel-shelf.git (fetch)
upstream	https://github.com/RichardLitt/the-travel-shelf.git (push)

```

**Comment by RichardLitt** [comment]
Ah. There we go. You need to pull from upstream - your fork is currently `origin`, which isn't useful, because we're not building off your fork, we're building off mine. So:

- Fetch all of the changes from upstream
- Make sure your master matches upstream/master
- Rebase onto upstream/master from your new branch
  - If there are conflicts, fix them. Commit or stash the results. 
- Push changes to this PR.

**Comment by Jojokats** [comment]
> You need to pull from upstream - your fork is currently origin, which isn't useful, because we're not building off your fork, we're building off mine.

Will have to research this :)

**Comment by RichardLitt** [comment]
> Will have to research this :)

Try `$ man git-remote` :)

**Comment by Jojokats** [comment]
> Try $ man git-remote :)

Ok, thanks!

**Comment by RichardLitt** [comment]
For the record: a friend of mine says that rebasing is _hard_ and uncommon. I disagree with the second part. But don't worry if this is tough!

**Comment by Jojokats** [comment]
> For the record: a friend of mine says that rebasing is hard and uncommon. 

I kinda agree with him :)
 I found this [link](https://help.github.com/articles/syncing-a-fork/) and am reading it, however it's scary to implement this since I have never done this before and am concerned about breaking something.

**Comment by RichardLitt** [comment]
Breaking is OK. You can always fix it again afterwards.

**Comment by Jojokats** [comment]
Thanks @RichardLitt for your patience and you encouraging me to not be afraid and experiment.  This has been very educational!  I fetched from your upstream/master, and made sure mine matched yours.  Then I was able to update my working branch and the conflict was gone!

**Comment by RichardLitt** [comment]
Nice! Now we just need to figure out why there are 17 commits in this PR. What commits do you _want_ to be in this PR?

**Comment by Jojokats** [comment]
> Nice! Now we just need to figure out why there are 17 commits in this PR. What commits do you want to be in this PR?

Not sure, should I requesting a list of commits and selecting them?

**Pull request closed without merging**
