### PR TITLE
Restructured the scss folder

### PR DESCRIPTION
**Pull request by Jojokats**
I would like to propose a cleaner architecture for the scss folder since we have a multipage site and things will get messy and cluttered really fast. 

Let me know what you think of this structure. 
Thanks!

### CODE REVIEW

**Comment by RichardLitt** [comment]
Perhaps do this after #90?

**Comment by Jojokats** [comment]
I prefer if possible before since this branch doesn't have any conflicts for now. After #90 it will.

**Comment by RichardLitt** [comment]
This has been merged! \o/

**Comment by Jojokats** [comment]
\o/

**Pull request closed without merging**
