### PR TITLE
Adding notes from today

### LINKED ISSUE #6: 20170919_Meeting Notes
Raw notes, no spellcheck nothing :D 

- boring business stuffs
- github Authentication 
- Windows Github stuffs

start 

People Present:
Hanie
Joanna
Jose
Richard 

Richard - Website about IDEPENDENT bookstors
	- Introduction about where the idea came from.
	-	Loves to travel, loves to code
	- What sort of website do we want to build??
	-	Directory of booksites which is BEAUTIFUL!!
	-	Great Photos
	-	Beautiful content
	-	Beautiful writting
	-		Messaging?
	-		User profiles?
	-		Admins??
	-		How big??

J	- What is the purpose??
	- Selling??

R	- There is a whole chain of indie bookstores that nobody knows about.	
	- BEING aware of all the indie bookstores in your area.
	- EVENTS - Author talks etc.
	- 	Newsletter
	- User profiles * locations based subscriptions to keep users 
	- 
V 	- What about coding spaces and bookshop features
	
R 	- Should be more like a catalog with Amedeties 

J 	- How do we get data???

R 	- Google API pull ?? Low quality
	- Quaratorial Features

J	- Whole Word??

R	- The US already indiebound. 
	- Connections with hackers groups over the word

H	- Alot like RBNB
	- User accounts for bookstores
	- Admin level

R	- Start with small features that work.
	- AIRBNB websites is hudge undertaking
	-V1	Map then page to bookstore
	-	Over engineer the website to be ready for the next versions
	- NODE, JS, DATABSE, Authentication ??
	- Build a website people like spending time

Newspapper style websites

R 	- <strong>Translation!!!<strong>
	- Bookpages?? Featured Books??

J 	- How are we going to take with the bookstore owners??

R	- CRM, APIS, Subsripbe to mailling lists??, Their APIs Start off easy with e-mail....No advertisements 

J	- Is this website going to make revenue??

R	- We don't know??

H	- Why don't make money?? 

J	- Lots of stuffs about money....

JS	- Find more people who are passionate

R 	- This will be free.
	- FINDING OTHER PEOPLE WHO WANT TO BE INVOLVED 
	- Building a community.
	- Build forums (Discuss)

R	- Literarly press
		- MVP

R	- Theuserisdrunk.com
	- For now MVP, what is Version 1.

V1	- No static website
		- Heavy lifting framework with database and routing, single page web app.
			- Python, jango, flask
			- Ruby on rails and ruby
			- JS & node 
R	- Backend - Homework: Three reasons for and against using each one of these language
	- Why not Java? Java is multithreaded 
	- Golang??
	- Elixer??
	- Spend a couple hours

H	- Javacsript is a popular language and Node is backend in JS

R 	- Front End - Framework ? 
	- Think about just using Jquery
	- Angular 4
	- React
	- Choo
	- Find one other front-end framework. 
	- Three pros and three negatives

J	- We can't use Vanilla JS, it's too long??

r	- Extract away the complexity
	-

H 	- The existing community!	

J	- We want job experience. 

G	- Be careful with information 

11:35 end of thingy

### PR DESCRIPTION
**Pull request by RichardLitt**
Closes #6

### CODE REVIEW

**Comment by RichardLitt** [comment]
@VernL How does this look? Take a look at 'Files changed' and let me know if it all seems good.

**Comment by VernL** [comment]
# Meeting @ Cafe Osmo, September 19, 2017

## Attendees:
- Hanie (H)
- Joanna (J)
- Jose (JS)
- Richard (R)
- Vernon (V)
- Guests:
  - _Greg_ (G)
  - _Jonathan_ (JO)

## Preface
- GitHub:
    - Command Line interface Authentication was discussed.
      - Required to make pull requests from the command line.
    - Windows GitHub & command line interface is to be figured out. 

## Agenda
- Define "The Travel Shelf" project as a group. 

## Meeting  
_start time approximately 10:00am_ 
- The idea was born from R's love to travel & to visit independent book stores.
- (R) There is a whole chain of indie bookstores that nobody knows about.
- (R) The purpose is to create a __beautiful__ directory of **Independent** Bookstores around the world to:
    - Help users be aware of indie bookstores in their area.
    - Keep track of __events__  such as author talks etc..
    - Create a community of indie bookstore lovers.
- (R) There is a whole chain of indie bookstores that nobody knows about.	
- The group discussed what kind of website we want to build:
  - Great photos, beautiful content, beautiful writing. 
    - (R) suggested the possibility of getting great writers instead of writing content ourselves. 
  - With **user profiles** to provide content based on their location.
  - _It may be possible to get info from bookstores by pulling data from newsletters._ 
  - The size and scope of the project was brainstormed, with possible features including:
    - Messaging, forums, User profiles, Admins.
  - _Shared work spaces fall outside the scope of this project as plenty of resources already exist_.
  - The issue  selling books and generating revenue from the site was discussed.
    - In general, it was not seen as a for profit project, rather a site ran by people who are __passionate__ about the cause and backed by a __dedicated__ community.
      - _There will need to be a way to find and maintain people who want to be involved with the project._  
    - If revenues would/could be generated, a non-profit approach would be preferred.
    - For the time being, the project will be more like a catalog of amenities for indie bookstores.
    - (R) explained that many free options exists for this project. Costs is no issue. 
  - Several options exist for getting the data:
    - Pulling from google API (Low quality) 
    - Collecting data ourselves or through bookstore owners and site users.
      - Would the project team play a curatorial role ?
      - Would bookstore owners or site users be free to create entries on their own?
      - A CRM for bookstore owners will be required.
      - Communication with bookstore owners will initially be handled via e-mail for simplicity. 
    - API's.
    - Newsletters.
  - The website will cover the whole world but will not focus on the US:
    - A great resource already exists [IndieBound](https://www.indiebound.org/)
    - It will be easier to get data in other parts in the world (through (R)'s contacts with hacker groups all over the world).
  - The site may be similar in style and features to Airbnb but with a __Newspaper__ style. 
    - User accounts for bookstore owners?
    - Admins?
  - Translation will be a huge complexity. 
    - Will be tackled in a future version. 
  - The possibility of having book pages and featured books was discussed.   
  - Build a website people like spending time on.
  

-  Version 1 (MVP) of the project was discussed. 
    - Start small with _beautiful_ features that work ( A full Airbnb style websites is hudge undertaking, can wait until Version 2 :) 
    - Show a map of bookstores with a clickable interface to access information about each bookstore. 
      - Could initially use data from google API (grayed out or scaled back) and have completed entrees stand out. 
  - Newspaper or magazine type of style. 
  - (R) explained that an MVP is all that is required for a project to be born adding several examples. (Literary press & theuserisdrunk.com).
  - The site will be over engineered to be ready for the next versions. 
    - Dynamic site, database, authentication.

The discussion changed it's course to focus on possibles technologies and languages that could be suitable for the project. After a discussion spanning a wide range of stacks, it was determined that we did not have sufficient knowledge to reach a proper decision and the topic will be revisited at a later date. A homework assignment was given to find three reasons for and against each language/technology discussed including:
 - Java
  - Golang
  - Elixer
  - Javacsript
  - Node
  - Vanilla JS vs Front end frameworks 
  - Angular 4
  - React 
  - Choo

___
_11:35am end of meeting_

**Comment by VernL** [comment]
@RichardLitt Please see Updated notes in previous comment. Will tackled this GitHub thing tomorrow :D 
Cheers,

**Comment by RichardLitt** [comment]
Thanks @VernL! Added the updated notes, committed, and merged.

**Pull request merged**
