### PR TITLE
Create basic landing page

### PR DESCRIPTION
**Pull request by ZJaf**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Let's work a bit more at this PR. What does `Kitty` in the title mean? Why is there no description of what you're doing in the PR (in the first comment?)

Recommended reading: [Writing good commit messages](https://github.com/erlang/otp/wiki/Writing-good-commit-messages), [writing good PRs](https://github.com/blog/1943-how-to-write-the-perfect-pull-request). 

Try editing the content above after reading these.

**Comment by ZJaf** [comment]
haha! Kitty!! well I didnt know how to choose a name! how to pull or even branch! this was a working branch!

On the index.js! I have updated the files. I havent push yet! I mentioned in another topic that I have lots of commits (as I am using express). So I was not sure if I should push or not. 

Thanks for the references. I will look at them and will get back to you probably with a new branch

**Comment by RichardLitt** [comment]
> well I didnt know how to choose a name! how to pull or even branch! this was a working branch!

Lots to learn. :) 

> I havent push yet! I mentioned in another topic that I have lots of commits (as I am using express). So I was not sure if I should push or not.

Generally, it's a good idea to push things into a PR if they meet the criteria set forward in an issue, _and no more_. Basically - if the issue says 'Make an index file', then make an index file. More than that isn't useful.

**Comment by ZJaf** [comment]
Im closing this branch. Opening a new one.

**Pull request closed without merging**
