### PR TITLE
Replace title tag and the image link

### PR DESCRIPTION
**Pull request by Jojokats**
Replaced the p tag of the images for a more semantic h3 tag in the portfolio section and included the correct image and image link in index.html.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Almost! I don't want to merge this PR, because I can't tell what it does from the title. Can you rename it? Remember how naming PRs is important - we talked about it [here](https://github.com/RichardLitt/the-travel-shelf/pull/36). 

Please rename this and all other open PRs.

**Comment by Jojokats** [comment]
I changed it to Modified-caption-content-header. Is this OK?

**Comment by RichardLitt** [comment]
Nope. It still says:

screen shot 2017-11-01 at 12 50 00

The PR name is not the branch name, is not the commit name.

**Comment by Jojokats** [comment]
I'm confused. I have to rename my branch, or create a new branch?

**Comment by RichardLitt** [comment]
Read what I wrote again please. Did I use the word branch?

**Comment by Jojokats** [comment]
ok, got it.

**Comment by RichardLitt** [comment]
I don't think you have. Please look into how to write good Pull Requests, and specifically how to write titles.

**Comment by Jojokats** [comment]
Modified title and description. Hope this is ok.

**Comment by RichardLitt** [comment]
Cool. I renamed it `Replace the p tag for an h3 tag`. However, that doesn't summarize what you did in both commits - you also change the worldmap. Maybe something more general?

**Comment by Jojokats** [comment]
> Maybe something more general?

Modified it, hope it's ok.

**Comment by RichardLitt** [comment]
Great! Shouldn't this also remove the old world image?

**Comment by Jojokats** [comment]
I removed the img/world.png and did the commit.

**Comment by RichardLitt** [comment]
> I removed the img/world.png and did the commit.

Hey @Jojokats. I'm not sure you have. The correct way to do this would be to add a commit to this branch, and then push it to this branch. It would automatically show up here, beneath my comment. You don't need to open a new PR for this.

**Comment by Jojokats** [comment]
I deleted it and did a commit. Now I did git status it's telling me I'm fine:
```
 git status
On branch feat/mapimage-better
Your branch is up-to-date with 'origin/feat/mapimage-better'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	config.codekit
	css/style.css.map
	index.js
	scss/.sass-cache/

nothing added to commit but untracked files present (use "git add" to track)
JoannaKats:the-travel-shelf joannakatsifaraki$ git push --set-upstream origin feat/mapimage-better
Branch feat/mapimage-better set up to track remote branch feat/mapimage-better from origin.
Everything up-to-date
```

**Comment by RichardLitt** [comment]
> On branch feat/mapimage-better

You need to put that commit on this branch, which is Jojokats:feat/headerstyle

**Comment by Jojokats** [comment]
> You need to put that commit on this branch, which is Jojokats:feat/headerstyle
I did this on this branch but not sure why it's not working.
 
```
git commit -m "deleted img/world.png"
On branch feat/headerstyle
Your branch is up-to-date with 'origin/feat/headerstyle'.
```

```
Branch feat/headerstyle set up to track remote branch feat/headerstyle from origin.
Everything up-to-date
JoannaKats:the-travel-shelf joannakatsifaraki$ git pull
Already up-to-date.
JoannaKats:the-travel-shelf joannakatsifaraki$ git merge origin/master
Already up-to-date.
JoannaKats:the-travel-shelf joannakatsifaraki$ git status
On branch feat/headerstyle
Your branch is up-to-date with 'origin/feat/headerstyle'.
```

**Comment by RichardLitt** [comment]
Push.

**Comment by Jojokats** [comment]
>Push.

```
 git push
Everything up-to-date
JoannaKats:the-travel-shelf joannakatsifaraki$ git push --set-upstream origin feat/headerstyle
Branch feat/headerstyle set up to track remote branch feat/headerstyle from origin.
Everything up-to-date
```

**Comment by RichardLitt** [comment]
Try just `git push origin feat/headerstyle`

And show me what you have for `git remote -v`, please. :)

**Comment by Jojokats** [comment]
>And show me what you have for git remote -v, please. :)

```
git push origin feat/headerstyle
Everything up-to-date
JoannaKats:the-travel-shelf joannakatsifaraki$ git remote -v
origin	https://github.com/Jojokats/the-travel-shelf.git (fetch)
origin	https://github.com/Jojokats/the-travel-shelf.git (push)
upstream	https://github.com/RichardLitt/the-travel-shelf.git (fetch)
upstream	https://github.com/RichardLitt/the-travel-shelf.git (push)
```

**Comment by RichardLitt** [comment]
Did you check the git graph? You should have two commits on this branch, and it should be two commits head of master.

**Comment by Jojokats** [comment]
> Did you check the git graph? You should have two commits on this branch, and it should be two commits head of master.

screen shot 2017-11-01 at 9 40 13 pm

**Comment by Jojokats** [comment]
Not sure how to read it.

screen shot 2017-11-01 at 9 41 55 pm

**Comment by RichardLitt** [comment]
When you make a new branch for a new PR, always go back to `master` first. That way, when you open your PR, you will only have the commits that are different than master (refer to the drawing I made - see how they all branch off of master?)

Your issue here is that you're on 1baf2a4, which is the same on feat/headerstyle. If you checkout f271e52 and push, then all of the commits between it and feat/headerstyle will be pushed to this branch. We don't want that. 

Look up how git checkout works. Note how you can checkout a branch and a commit -because a branch just points to a commit, nothing more. Trying checking out 1baf2a4, commiting f271e52 changes (deleting img/world) again on branch feat/headerstyle, and then push the changes to origin/feat/headerstyle.

**Comment by Jojokats** [comment]
> You need to put that commit on this branch, which is Jojokats:feat/headerstyle

You asked me previously to work on this branch `feat/headerstyle `which I have been doing. 
but it's not working. I will try again to checkout here and `delete img/world.png` again and then `push to origin/feat/headerstyle`  and I will give you news.

**Comment by Jojokats** [comment]
I did everything you asked, and it's not working :(
```
git rm img/world.png
rm 'img/world.png'
JoannaKats:the-travel-shelf joannakatsifaraki$ git status
On branch feat/headerstyle
Your branch is up-to-date with 'origin/feat/headerstyle'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    img/world.png

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	config.codekit
	css/style.css.map
	index.js
	scss/.sass-cache/

JoannaKats:the-travel-shelf joannakatsifaraki$ git commit -m "deleting world.png"
[feat/headerstyle 9a87ea2] deleting world.png
```

```
git status
On branch feat/headerstyle
Your branch is ahead of 'origin/feat/headerstyle' by 1 commit.
```
I did a git push origin feat/headerstyle also.

**Comment by RichardLitt** [comment]
It is working. You pushed it above, in commit 9a87ea2. Now there are three commits in this branch, which is how it should be. 

Could you show me the git graph again? I want to be able to point out how the branch looks. :)

**Comment by Jojokats** [comment]
Hey @RichardLitt I'm glad you're seeing the light. lol
I have to step out so I will be sending you the graph and continuing this afternoon.  
Thanks for your patience!  :)

**Comment by Jojokats** [comment]
> Could you show me the git graph again? I want to be able to point out how the branch looks. :)

Hey @RichardLitt , apologies for the delay!
Here is the graph you requested. 

graph-nov-2


Please advise what steps to take now,
Thanks!

**Comment by RichardLitt** [comment]
Great. Do you see how 9a87ea2 is based on 1baf2a4, and that on {one more and then} master? That's what it should look like.

**Comment by Jojokats** [comment]
> Great. Do you see how 9a87ea2 is based on 1baf2a4, and that on {one more and then} master? That's what it should look like.

Honestly, I'm having difficulty reading and understanding how the graph works.

**Comment by Jojokats** [comment]
I will work on modifying the other titles and descriptions of the branches I made as well.

**Comment by RichardLitt** [comment]
> Honestly, I'm having difficulty reading and understanding how the graph works, but glad it got sorted out!

The graph should be pretty simple to read, if you understand what branches are. If you don't, I really encourage you to read more, as the issue won't go away on its own.

**Comment by Jojokats** [comment]
> The graph should be pretty simple to read, if you understand what branches are. If you don't, I really encourage you to read more, as the issue won't go away on its own.

Will look into this graphs

**Pull request merged**
