### PR TITLE
Coded the Contact.js and Sass files

### PR DESCRIPTION
**Pull request by Jojokats**
Coded the Contact.js, Sass and the Footer component in React.js

### CODE REVIEW

**Comment by Jojokats** [comment]
@RichardLitt , there is a conflict in this PR, any suggestions or recommendations on what to do next to fix this?

**Comment by RichardLitt** [comment]
You need to rebase it on `master`, first. Then repush to this branch.

**Comment by Jojokats** [comment]
ok, will try this

**Comment by Jojokats** [comment]
I looked into it and will follow these instructions: 
* git checkout myBranch
* git rebase master
* git checkout master
* git merge myBranch

Can you tell me if this is correct?
Thanks!

**Comment by RichardLitt** [comment]
You're going to have to figure this one out. There will be no conflict once you understand rebasing. The only thing you could mess up would be pushing to master, or erasing your work on a branch. Keep it backed up in another branch somewhere to make sure that doesn't happen.

**Comment by Jojokats** [comment]
:(

**Comment by RichardLitt** [comment]
:) What a great opportunity to learn. I've explained rebasing many times now. I am confident you can do it.

**Comment by Jojokats** [comment]
I've watched you do it, but I learn better by actually coding along. Anyhow, I am experiencing issues and I'm stuck. I got this
```First, rewinding head to replay your work on top of it...
Applying: Coded the Contact.js and Sass files
Using index info to reconstruct a base tree...
M	src/App.js
M	src/components/Navbar/Navbar.js
.git/rebase-apply/patch:78: trailing whitespace.
     </footer>    
.git/rebase-apply/patch:224: space before tab in indent.
                	<h1 className="display-4 myhero text-center">Contact</h1>
warning: 2 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging src/components/Navbar/Navbar.js
Auto-merging src/App.js
CONFLICT (content): Merge conflict in src/App.js
error: Failed to merge in the changes.
Patch failed at 0001 Coded the Contact.js and Sass files
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

**Comment by RichardLitt** [comment]
Great. Errors means you're doing something right. Figure out how to fix them.

**Comment by Jojokats** [comment]
I kinda gave up, I'm creating a new branch and starting over

**Comment by RichardLitt** [comment]
I would strongly encourage you not to give up, but to find a way to enjoy figuring out the solution.

**Comment by Jojokats** [comment]
It's Greek to me (I can say Greek, cause I'm Greek/Canadian).
Don't know what to google for this:
```
warning: 2 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging src/components/Navbar/Navbar.js
Auto-merging src/App.js
```

**Comment by RichardLitt** [comment]
I spent three years learning classical Greek. "It's all Greek to me" just means you haven't used your dictionary enough. 😛 

Those two lines don't look like an issue. Google tutorials if you're having issue with how to rebase. I do not have the time to hand-hold you on this.

**Comment by Jojokats** [comment]
Very impressive, that you learned classical Greek! I speak and write Greek myself.

Anyhow, I understand you're busy and I will try to fix this but if it won't work, I'll just restart
Thanks!

**Comment by VernL** [comment]
CONFLICT (content): Merge conflict in src/App.js => Open APP.js, resolve the merge conflict by choosing the code you want to keep and removing the =======. Save the file. then you can continue with git rebase --continue

**Comment by Jojokats** [comment]
thanks but I'm working in a different branch now and have corrected image file paths and variable codes so I think I will just continue here. Thanks

**Pull request closed without merging**
