### PR TITLE
feat: Add react-remarkable package

### PR DESCRIPTION
**Pull request by VernL**
A commit from a pending pull request is included. I'm curious to see if it will sort itself out.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Why is there an extra commit? :P

**Comment by VernL** [comment]
Because I created this branch off of #115 instead of reverting to master which will become "outdated" once #115 is accepted :D

**Comment by VernL** [comment]
The extra commit is the commit from #115. Instead of reverting to master to begin working on this PR, I created this branch from #115. Once the previous PR is accepted, the duplicate commit should disappear :D

**Comment by VernL** [comment]
I just wanted to see what would happen. It won't work anymore as the previous commit has changed.

**Comment by RichardLitt** [comment]
Pardon. Yes, I think what you said should happen should happen.

**Pull request closed without merging**
