### PR TITLE
Add "Drawn and Quarterly" review

### PR DESCRIPTION
**Pull request by RichardLitt**
I've added in my review of _Drawn and Quarterly_. Might edit it later, but here is the basic idea. What do you think? @VernL and @ZJaf - what should I add to the data object?

### CODE REVIEW

**Comment by ZJaf** [comment]
I like the post, Just the ideas as below:
- Languages supported: English? French?
- Payment methods: Credit? Cash? Debit?
- Contact information?

**Comment by RichardLitt** [comment]
Good questions. Should be in the JSON.

**Comment by VernL** [comment]
Nice Work! I'd just add __Seating space__ and __URL__ to the JSON and it looks good to me. 
Few extra thoughts: 
- I also notice they have events listed on [Facebook,](https://www.facebook.com/pg/LibrairieDandQ/events/) maybe we can use this somehow ?
- Do we want to provide contact information directly on our site or simply link to their website?

**Comment by Jojokats** [comment]
I really like your article, it is well written and gives you the urge to visit this bookstore!

Good point @VernL regarding the events. Do we list them ourselves for now or link them to their Facebook page?

**Comment by RichardLitt** [comment]
Linking to their website makes more sense. 

Let's make a specification for how the JSON schema should look. We can use [mongoose](https://github.com/Automattic/mongoose) for this. Anyone want to take no making data schemas?

**Comment by VernL** [comment]
@RichardLitt I'm on it. I suggest we host our data using the (free) sandbox plan on [mLab](https://www.mlab.com/plans/pricing/). It will avoid setting up mongoDB on everyones machines as well as it provides some nice tools for data visualization. For this, I can create an account using a generic gmail account such as the-travel-shelf@gmail.com. Sound ok?

**Comment by RichardLitt** [comment]
Maybe use richard@thetravelshelf.com? I've set that up. I can forward emails to you, as needed.

**Pull request merged**
